alias cfgst="config status"
alias cfgpl="config pull"
alias cfgplr="config pull --rebase"
alias cfgps="config push"
alias cfga="config add"
alias cfgaa="config add -A"
alias cfgco="config checkout"
alias cfgcm="config commit -m"
alias cfgcam="config commit -am"

alias shutdown="sudo shutdown"
